#!/usr/bin/env python3
"""Build the colour layer of mixxx/skins/Terminal-wide from a palette.

    python tools/generate.py              # all palettes
    python tools/generate.py --palette btop
    python tools/generate.py --check      # write nothing, fail if stale

Qt stylesheets have no variables and Mixxx picks a colour scheme by pointing at
a different stylesheet, so "make the colours adjustable" means generating one
stylesheet per scheme. The palette JSON is the single source of truth; the
per-scheme stylesheets and the <Schemes> block in skin.xml are derived from it
and should never be hand-edited.

Terminal-wide ships no image assets, which is why this is a fraction of the
size of the Terminal skin's own generator in the Mixxx tree: there are no icon
SVGs to flatten and repaint, only text on blocks.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
SKIN = REPO / "Terminal-wide"
SKIN_XML = SKIN / "skin.xml"

SCHEMES_BEGIN = (
    "  <!-- TERMINAL-WIDE-SCHEMES-BEGIN: generated by"
    " tools/generate.py, do not edit -->"
)
SCHEMES_END = "  <!-- TERMINAL-WIDE-SCHEMES-END -->"

TOKEN_RE = re.compile(r"\{\{([a-z0-9_]+)\}\}")


class Palette:
    """A colour scheme: raw colours plus the roles that point at them."""

    def __init__(self, data: dict):
        self.name = data["name"]
        self.dir = data["dir"]
        self.description = data.get("description", "")
        # A single-hue palette. Cue and track colours come from the user's
        # colour palette rather than from here, and a scheme with one hue has
        # nowhere to put them, so it opts out of them.
        self.mono = bool(data.get("mono", False))
        self.colors = dict(data["colors"])
        self.roles = {}
        for role, key in data.get("roles", {}).items():
            if key not in self.colors:
                raise SystemExit(
                    f"palette {self.name}: role {role!r} -> unknown colour {key!r}"
                )
            self.roles[role] = self.colors[key]

    def tokens(self) -> dict:
        merged = dict(self.colors)
        merged.update(self.roles)
        merged.update(
            {
                "scheme_name": self.name,
                "scheme_dir": self.dir,
                "scheme_description": xml_comment_safe(self.description),
                # See the comments on these in the templates.
                "hide_track_color": "true" if self.mono else "false",
                "use_cue_color": "false" if self.mono else "true",
                "track_color_opacity": "0" if self.mono else "0.175",
            }
        )
        return merged


def load_palettes(only: str | None) -> list[Palette]:
    found = []
    for path in sorted((HERE / "palettes").glob("*.json")):
        if only and path.stem != only:
            continue
        found.append(Palette(json.loads(path.read_text(encoding="utf-8"))))
    if not found:
        raise SystemExit(f"no palette matched {only!r} in {HERE / 'palettes'}")
    return found


def xml_comment_safe(text: str) -> str:
    """A '--' anywhere inside an XML comment makes the document invalid, and
    prose hits that easily. Mixxx reacts to a malformed skin.xml by logging one
    debug line and loading its default skin, which looks like the skin simply
    not being listed rather than an error - so this is worth guarding."""
    return text.replace("--", "-").rstrip("-")


def render(template: str, tokens: dict, where: str) -> str:
    """Substitute {{token}}. An unknown token is an error rather than a
    silently unstyled widget."""

    def sub(match: re.Match) -> str:
        key = match.group(1)
        if key not in tokens:
            raise SystemExit(f"{where}: unknown token {{{{{key}}}}}")
        return tokens[key]

    return TOKEN_RE.sub(sub, template)


def write(path: Path, text: str, check: bool, stale: list) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == text:
        return
    if check:
        stale.append(path.relative_to(REPO).as_posix())
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO).as_posix()}")


def build_qss(palettes: list[Palette], check: bool, stale: list) -> None:
    template = (HERE / "templates" / "style.qss.in").read_text(encoding="utf-8")
    for palette in palettes:
        text = render(template, palette.tokens(), f"style.qss.in [{palette.name}]")
        write(SKIN / f"style_{palette.dir}.qss", text, check, stale)


def build_skin_xml(palettes: list[Palette], check: bool, stale: list) -> None:
    """Splice the <Scheme> blocks into skin.xml between the markers.

    Always writes every palette, not just a --palette subset: the block is one
    region of one file, and rewriting it from a filtered list would drop the
    schemes that were filtered out."""
    template = (HERE / "templates" / "scheme.xml.in").read_text(encoding="utf-8")
    blocks = [
        render(template, p.tokens(), f"scheme.xml.in [{p.name}]").rstrip("\n")
        for p in palettes
    ]

    original = SKIN_XML.read_text(encoding="utf-8")
    start = original.find(SCHEMES_BEGIN)
    end = original.find(SCHEMES_END)
    if start == -1 or end == -1:
        raise SystemExit(f"{SKIN_XML}: scheme markers not found")

    body = "\n".join(blocks)
    text = (
        original[: start + len(SCHEMES_BEGIN)]
        + "\n"
        + body
        + "\n"
        + original[end:]
    )

    # A skin.xml that does not parse fails silently at runtime, so never let a
    # broken one reach disk.
    try:
        ET.fromstring(text)
    except ET.ParseError as exc:
        raise SystemExit(f"{SKIN_XML}: generated XML is not well-formed: {exc}")

    write(SKIN_XML, text, check, stale)


def sync_library_icons(source: Path, check: bool, stale: list) -> None:
    """Vendor the library sidebar icons from the Terminal skin in a Mixxx tree.

    The sidebar icons are not styleable from a stylesheet: a LibraryFeature
    builds a QIcon, and the only handle a skin has is to ship a replacement at
    `<skin>/library/<scheme>/ic_library_<name>.svg` (libraryfeature.cpp,
    skinIconPath). Without one the sidebar keeps Mixxx's saturated orange,
    which on a green-phosphor scheme is the only colour on the screen.

    Terminal already generates exactly this set, from exactly these palettes,
    by flattening Mixxx's own icons and repainting them - so the icons are
    copied rather than regenerated here. This repo has no Mixxx source tree to
    flatten them from, and duplicating that machinery to produce identical
    output would be the worse trade.

    Point --from-terminal at a Mixxx checkout that carries the Terminal skin
    and re-run after changing a palette, or the icons and the stylesheets drift
    apart.
    """
    src_root = source / "res" / "skins" / "Terminal" / "library"
    if not src_root.is_dir():
        raise SystemExit(f"no Terminal library icons at {src_root}")
    dst_root = SKIN / "library"
    for src in sorted(src_root.rglob("*.svg")):
        dst = dst_root / src.relative_to(src_root)
        write(dst, src.read_text(encoding="utf-8"), check, stale)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--palette",
        help="only rebuild this palette's stylesheet (by file stem, e.g. btop)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit non-zero if any generated file is out of date",
    )
    parser.add_argument(
        "--from-terminal",
        metavar="MIXXX_TREE",
        type=Path,
        help="also refresh library/ from res/skins/Terminal/library in this"
        " Mixxx checkout (see sync_library_icons)",
    )
    args = parser.parse_args()

    all_palettes = load_palettes(None)
    selected = load_palettes(args.palette)

    stale: list = []
    build_qss(selected, args.check, stale)
    build_skin_xml(all_palettes, args.check, stale)
    if args.from_terminal:
        sync_library_icons(args.from_terminal, args.check, stale)

    if args.check and stale:
        print("out of date:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("run: python tools/generate.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
